Task/nxc 49 selectors
next-cart-dev/design-system pull request #10
Opened 2022-08-08 16:54 UTC by DehLuizSantos

# Descrição

Components de seletores: RadioGroup, Select e Switch feitos com RadixUi

Os components contem storybook, testes de mock, tipagens e Styles personalizados com stitches.

Lembrando que os testes unitarios não estão passando, devido a um "bug" do React, já estou falando com o @pedro-cartco para tentar ajustar uma solução para este problema.

Task # [NXC-49](https://cartco.atlassian.net/jira/software/projects/NXC/boards/1?selectedIssue=NXC-49)

## Tipo de alteração

- [ ] Correção de bug
- [ ] Melhoria
- [X] Novo componente

# Checklist:

- [X] Meu código segue as diretrizes de estilo deste projeto
- [X] Realizei uma auto-revisão do meu próprio código
- [X] Eu comentei meu código, particularmente em áreas difíceis de entender
- [X] Fiz as alterações correspondentes na documentação
- [ ] Minhas alterações não geram novos erros
- [X] Adicionei testes que comprovam que minha correção é eficaz ou que minha feature funciona
- [ ] Testes unitários novos e existentes continuam passando localmente com minhas alterações

2022-08-08 18:14 UTC, daniloras requested changes
@DehLuizSantos anotei alguns pontos,

Somente o visual do CHECKBOX, particularmente achei bem pequeno.

2022-08-08 18:14 UTC, daniloras commented on src/CheckBox/styles.ts
> +  transition: "box-shadow 0.3s ease-in-out, #39296C 0.1s ease-in-out",
@DehLuizSantos esse Hexadecimal? Acredito que deve ser contemplado nos tokens.

2022-08-08 18:14 UTC, daniloras commented on src/CheckBox/styles.ts
> +    boxShadow: "0 0 0 1px #39296C"
@DehLuizSantos esse Hexadecimal? Acredito que deve ser contemplado nos tokens.

2022-08-08 18:14 UTC, daniloras commented on src/RadioGroup/styles.ts
> +  boxShadow: "0 0 0 1px #39296C",
@DehLuizSantos esse Hexadecimal? Acredito que deve ser contemplado nos tokens.

2022-08-08 18:14 UTC, daniloras commented on src/RadioGroup/styles.ts
> +    boxShadow: "0 0 0 2px #39296C"
@DehLuizSantos esse Hexadecimal? Acredito que deve ser contemplado nos tokens.

2022-08-08 18:14 UTC, daniloras commented on src/RadioGroup/styles.ts
> +    boxShadow: "0 0 0 2px #39296C"
@DehLuizSantos esse Hexadecimal? Acredito que deve ser contemplado nos tokens.

2022-08-08 18:14 UTC, daniloras commented on src/RadioGroup/styles.ts
> +    boxShadow: "0 0 0 2px #D2D4DA"
@DehLuizSantos esse Hexadecimal? Acredito que deve ser contemplado nos tokens.

2022-08-08 18:14 UTC, daniloras commented on src/Switch/styles.ts
> +        backgroundColor: /* "$neutral600" */ "#ABA6C2",
@DehLuizSantos esse Hexadecimal? Acredito que deve ser contemplado nos tokens.

2022-08-08 18:14 UTC, daniloras commented on src/Switch/styles.ts
> +        backgroundColor: /* "$neutral600" */ "#DBDBDB",
@DehLuizSantos esse Hexadecimal? Acredito que deve ser contemplado nos tokens.

2022-08-09 22:21 UTC, DehLuizSantos commented on src/CheckBox/styles.ts
> +  transition: "box-shadow 0.3s ease-in-out, #39296C 0.1s ease-in-out",
Aumentei o Checkbox para 20px de width e height, ficou melhor!. 
Ajustei todos hexadecimais para variavies de ambiente conforme solução feita pelo Pedro

2022-08-10 13:35 UTC, pedro-cartco commented
A integração com `react-hook-form` foi validada? Deu tudo certo ou surgiu algum erro?

2022-08-25 14:19 UTC, closed without merging